apiVersion: v1
kind: Service
metadata:
  name: ghostbuster-http
  namespace: ghostbuster

spec:
  selector:
    app: ghostbuster-http
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
