apiVersion: v1
kind: Service
metadata:
  name: ghostbuster-grpc
  namespace: ghostbuster
spec:
  selector:
    app: ghostbuster-grpc
  ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051
